import "./globals.css";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import { TRPCReactProvider } from "~/uploadthing/react";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Montserrat({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${geist.variable}`} lang="en">
			<body className="font-sans">
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}
